### PR TITLE
Re-design lobby button functionality and look

### PR DESCRIPTION
**Pull request by DavidCuevas3**
Re-designed the look and functionality of the lobby button in game state.

Previous button functionality:
image

New button functionality:
image

### CODE REVIEW

**Comment by igrv2003** [comment]
LGTM 
image

**Review by igrv2003 — APPROVED** [review]
LGTM

image

**Review by PinkSylvie — APPROVED** [review]
Works nicely on my side!

**Comment by AngelCIICMorales** [comment]
Looks nice!

**Pull request merged**
