### PR TITLE
Added the new asset and implemented it

### PR DESCRIPTION
**Pull request by Saul-Caban-UPRM**
I've recently updated the Domino tile resources for the game so that they're aligned with the overall look of the web site. The new tile design integrates colors and textures that correspond to the site's style, improving the consistency and creating a more coherent image.

### CODE REVIEW

**Comment by AngelCIICMorales** [comment]
Please provide a more detailed description.

**Comment by AngelCIICMorales** [comment]
image
I believe these colors are too bright. The darker INSO looked better. I think the rest of the changes are fine.

**Comment by AngelCIICMorales** [comment]
> image I believe these colors are too bright. The darker INSO looked better. I think the rest of the changes are fine.

I want to specify that I mean the colors on the word INSO are too bright in contrast with the rest of the tile.

**Comment by Saul-Caban-UPRM** [comment]
I have changed the back of the tile to still match the tile colors and border, but the word INSO is now back to it's original color.
new-backtile

**Review by AngelCIICMorales — APPROVED** [review]
LGTM

**Review by PinkSylvie — APPROVED** [review]
Looks great!

**Pull request merged**
