### PR TITLE
338 adding UI sounds to homepage

### PR DESCRIPTION
**Pull request by Joaquin939**
In this issue I was able to implement UI sounds for when a user clicks a button on the home page. 
This was achieved by creating a reusable playSound function that accesses an audio file. The function is triggered through the onClick event of various buttons and links across the application.

### CODE REVIEW

**Review by AngelCIICMorales — CHANGES_REQUESTED** [review]
You used the same sound effect as the domino placement tile. Please use a different sound effect. Also, I'm not sure if it's because your branch is old, but I noticed that when I click on parts of the homepage, they don't relocate to the instructions or guidelines like they used too. Additionally, 20 points for this task is asking a bit too much. If you go above and beyond, we can negotiate this many points.

**Comment by Joaquin939** [comment]
> You used the same sound effect as the domino placement tile. Please use a different sound effect. Also, I'm not sure if it's because your branch is old, but I noticed that when I click on parts of the homepage, they don't relocate to the instructions or guidelines like they used too. Additionally, 20 points for this task is asking a bit too much. If you go above and beyond, we can negotiate this many points.

If you read the files you can clearly see they are different sounds. One is for clicks and one is for the placement of the domino. Adding different UI sounds for button clicks in the same project can create inconsistency and confusion for users. It disrupts the overall design cohesion, making the interface feel less polished and harder to navigate. Users rely on predictable feedback to build familiarity with an interface, and varying sounds can dilute this sense of reliability, leading to frustration or a less intuitive experience. I hope this cleared any confusion on this. Here are the screenshots just in case. 
Whatever else you are talking about the homepage instructions that has nothing to do with this issue, as you can see the changes I've made are only about adding the sounds for clicks. And the point deduction would be uncalled for because it involves creating, selecting, and syncing appropriate sounds for various interactions, significantly enhancing the user experience. This task adds a crucial layer of feedback and polish to the game, requiring both technical expertise and creative effort, especially since the project previously had no audio foundation.

Screenshot 2024-11-23 at 11 11 57 AM
Screenshot 2024-11-23 at 11 12 07 AM

**Comment by AngelCIICMorales** [comment]
I must have misremembered the sound effect. I know realize you used the instructions sound effect which is why it sounded familiar to me. Also, if you read my message, I stated the I believed the reason the redirects were because the branch was old, which upon another loo, it is. Please update the branch to make sure it works with the newest version of the main.

**Comment by AngelCIICMorales** [comment]
On another note, the sound effect does not play when you press the sign in button, or the sign-up button, or the log in button, or any button outside the homepage for that matter. Could you expand the scope of the issue and do that please?

**Comment by Joaquin939** [comment]
> On another note, the sound effect does not play when you press the sign in button, or the sign-up button, or the log in button, or any button outside the homepage for that matter. Could you expand the scope of the issue and do that please?

In my latest commit, I updated the branch to the latest version of main, and I expanded the scope of the issue and added the UI sounds to the login/signup pages and the forgot password page. I noticed what you said about some buttons not playing the sound and upon further inspection, those appear to be the buttons for when a state of the game changes. For example, if you are in the home page and you click home, no sound will be produced since it basically refreshes the page. And the same goes for the other buttons that change the state of the game. If you are at the home page and you click the _signup/login button_ ,the _gamestate_ changes too fast for the _playsound_ function to run. I hope that clears that confusion. Other than that, I implemented and fixed everything you asked for in my latest commit.

**Comment by AngelCIICMorales** [comment]
The sounds work on the sign in page. However, I still noticed that the sounds in the lobby selection screen have not been implemented. Also, while comparing the current main with your branch, it still seems that your branch is still using an older homepage.
image
image
While checking the redirects I noticed there was no way to go back to the homepage after clicking on them.  
If you can add the sounds for the lobby screen and the game state and make sure the sounds work on the new homepage while adding a way to redirect from the privacy policy screen etc. to the homepage I will give you 20 points.

**Comment by Joaquin939** [comment]
> The sounds work on the sign in page. However, I still noticed that the sounds in the lobby selection screen have not been implemented. Also, while comparing the current main with your branch, it still seems that your branch is still using an older homepage. image image While checking the redirects I noticed there was no way to go back to the homepage after clicking on them. If you can add the sounds for the lobby screen and the game state and make sure the sounds work on the new homepage while adding a way to redirect from the privacy policy screen etc. to the homepage I will give you 20 points.

The lobby sounds were implemented in a previous issue. If they somehow stopped working, I have no idea why that is, and that has nothing to do with the issue at hand. It could be possible that like I mentioned before, there may be some buttons inside the lobby selection that change the state of the game. Like when you join a new lobby which basically creates a new game. That change happens so fast, there is no time for the _playsound_ function to run.  The redirect from the privacy policy screen to the homepage is also out of scope for this issue and that is something I will not be working on. It also seems like for some reason my branch won't update with main, so I'll finish working on this on another branch.

**Comment by Joaquin939** [comment]
What I think I'll end up doing since nothing works, I'll close this pull request and reopen another branch that is already up to date with main.

**Pull request closed without merging**
