### PR TITLE
User Object created

### PR DESCRIPTION
**Pull request by JadiellMV**
User object added, please let me know if there's anything to add/improve before merging!

### CODE REVIEW

**Comment by AngelCIICMorales** [comment]
Can you please elaborate on what you added?

**Comment by JadiellMV** [comment]
> Can you please elaborate on what you added?

I added a User class that represents a user profile with several attributes and methods for managing the user's data. I included a username, email, password, scores, match history, and game achievements attributes along with different methods that help update such attributes. The goal was to have a centralized structure that would make managing user-related data simpler, and also easy to update if necessary.

**Review by AngelCIICMorales — APPROVED** [review]
LGTM.

**Review by Keiven-Soto — APPROVED** [review]
looks good

**Review by fernandopizarro1 — APPROVED** [review]
LGTM!

**Pull request merged**
