### PR TITLE
Improving Domino Visuals and Orientation

### PR DESCRIPTION
**Pull request by G4vp**
Fixed the issue where dominoes placed on the table were not in the correct orientation, ensuring the numbers match with their neighbors. Additionally, added functionality for dominoes placed vertically to rotate 90 degrees and align with their neighbors, making the game more realistic.

Screenshot from 2024-11-22 19-59-19

### CODE REVIEW

**Review by fernandopizarro1 — APPROVED** [review]
Nice job! 👍

**Comment by AngelCIICMorales** [comment]
This is the most beautiful thing I have ever seen.
image

**Comment by AngelCIICMorales** [comment]
My happiness is indescribable. I never thought this day would come.

**Review by AngelCIICMorales — APPROVED** [review]
LGTM

**Pull request merged**
