### PR TITLE
Added Lobby Id generation, server functionaliy and invites

### PR DESCRIPTION
**Pull request by ebrain-mendoza121**
Includes server.js in frontend folder that handles connections on lobby page. :
To run working server:
On a new terminal inside frontend folder run: 
`node server.js`
That should produce the following output:
`Server running at http://localhost:5000`

On a new terminal run npm start on the frontend.
On lobby page you will have options to create, and see public lobbies. Create and and option to input private lobby code. 

image
image

By taking the code in the route that appears in the route, and pasting it in the input field for lobby code the player should be redirected to private lobby.

### CODE REVIEW

**Comment by AngelCIICMorales** [comment]
Could you enter a call so we can test this?

**Comment by AngelCIICMorales** [comment]
Also please fix the conflict.

**Comment by AngelCIICMorales** [comment]
abroad@LAPTOP-54IVI1AE:/mnt/c/Users/Angel/Desktop/Experiment/semester-project-multiplayer-dominoes/frontend$ node server.js
/mnt/c/Users/Angel/Desktop/Experiment/semester-project-multiplayer-dominoes/frontend/server.js:153
import express from "express";
       ^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by ebrain-mendoza121** [comment]
const express = require("express");

**Review by AngelCIICMorales — APPROVED** [review]
LGTM

**Review by Negroni1 — APPROVED** [review]
LGTM

**Pull request merged**
