### PR TITLE
Implemented Game Overlays

### PR DESCRIPTION
**Pull request by igrv2003**
Added the images for the game overlays, also implemented the logic for how and when the game overlays are displayed.

### CODE REVIEW

**Review by AngelCIICMorales — CHANGES_REQUESTED** [review]
For some reason I only see the placeholder and not the image itself.

**Comment by PinkSylvie** [comment]
I can't see the images themselves either

**Comment by igrv2003** [comment]
Fixed it:
Screenshot 2024-10-07 at 8 48 49 PM

Screenshot 2024-10-07 at 8 30 18 PM

**Review by AngelCIICMorales — CHANGES_REQUESTED** [review]
Please fix the merge conflicts.

**Comment by igrv2003** [comment]
> Please fix the merge conflicts.

Done.

**Review by AngelCIICMorales — APPROVED** [review]
LGTM

**Review by PinkSylvie — APPROVED** [review]
Works and looks great now!

**Pull request merged**
