### PR TITLE
Creation of the IntermediateBot

### PR DESCRIPTION
**Pull request by fernandopizarro1**
Created a new Intermediate Bot that inherits from the Simple Domino Bot #151 . The difference from both bots is that this bot looks for the highes playable tile from their hand, and uses that tile.

### CODE REVIEW

**Review by Gaby-Concepcion — APPROVED** [review]
The class functionality and implementation look good!

**Comment by AngelCIICMorales** [comment]
What happened to the original bot? Is there a way to alternate between them?

**Comment by AngelCIICMorales** [comment]
image

**Review by AngelCIICMorales — CHANGES_REQUESTED** [review]
The placement of tiles seems to be bugged, and I encounter an error at the end of a game.

**Comment by fernandopizarro1** [comment]
> The placement of tiles seems to be bugged, and I encounter an error at the end of a game.

The error seems to be fixed, however, it seems that the bug is not from the IntermediateBot, and more of a problem from the game logic itself. I asked @nsfrontera to look into it. I will also look into it myself.

**Comment by fernandopizarro1** [comment]
> What happened to the original bot? Is there a way to alternate between them?

@AngelCIICMorales right now there is no way to alternate between them, but that could be worked on in another issue, possibly with the lobby creation and maybe when implementing the screen to select a game.

**Review by AngelCIICMorales — APPROVED** [review]
LGTM

**Pull request merged**
