### PR TITLE
15 - Added unit testing

### PR DESCRIPTION
**Pull request by Jvstinoo**
Added unit testing for Table and Bot logic. 

Table testing:
- When choosing valid domino, places it correctly.
- When choosing invalid domino, ignores it.
- No duplicate dominoes are created when calling `grabRandomChip`.

Bot testing:
- Chooses correct domino based on wanted logic (should choose first valid domino on hand).
- Returns null when bot has no dominoes to choose from (can't play).

### CODE REVIEW

**Review by fernandopizarro1 — CHANGES_REQUESTED** [review]
Everything looks good. However, there are merge conflicts so please fix those.

**Comment by Jvstinoo** [comment]
> Everything looks good. However, there are merge conflicts so please fix those.

Fixed merge conflicts, should be good now!

**Review by fernandopizarro1 — APPROVED** [review]
LGTM!

**Review by AngelCIICMorales — APPROVED** [review]
LGTM.

**Pull request merged**
