### PR TITLE
408 finishing UI sounds implementations

### PR DESCRIPTION
**Pull request by Joaquin939**
In this issue I will work on finishing the UI sounds implementations for the Home, Login, Forgot password, Lobby, and the main pages of the game.

### CODE REVIEW

**Review by DavidCuevas3 — APPROVED** [review]
Lgtm. The sounds add a lot of life to the game.

**Comment by AngelCIICMorales** [comment]
Please add description.

**Comment by Joaquin939** [comment]
I completed the Home, Login, Forgot password, Lobby, and the main pages of the game. Additionally I added a missing button to redirect back to the homepage from the login page. As requested I added a different sounds for the buttons inside the game state and they are already uploaded to the project's google drive.

**Review by AngelCIICMorales — APPROVED** [review]
LGTM

**Pull request merged**
