### PR TITLE
Implemented the UI sound for when a domino is placed

### PR DESCRIPTION
**Pull request by Joaquin939**
Correctly implemented the UI sound for when a domino is placed by the bot and the player.

### CODE REVIEW

**Review by AngelCIICMorales — CHANGES_REQUESTED** [review]
Please combine this pull request with the prior one.

**Comment by Joaquin939** [comment]
> Please combine this pull request with the prior one.

Since the prior one was closed, I changed the code so it's up to date with main.

**Review by AngelCIICMorales — APPROVED** [review]
LGTM

**Comment by PinkSylvie** [comment]
It works great but I am concerned of a an error that appears once I jump to the lobby while I was playing a game and then I try to got back to the game. I don't think it is an issue with your code but more of an error from the gamestate's part. @AngelCIICMorales 
image

**Review by PinkSylvie — APPROVED** [review]
The code looks great and everything works! I'm concerned on a bug that is appearing but is on the main branch so it isn't related to your work and this should be fine to merge.

**Pull request merged**
