### PR TITLE
Modified buttons and text in Game State to match game aesthetic

### PR DESCRIPTION
**Pull request by DavidCuevas3**
### **Made the following changes to the Game State:**

- Modified the main game control buttons to match with the rest of the game of aesthetic; previously the buttons had a basic appearance that did not reflect the playful nature of the game.
- Modified the font of non-button main text such as "Volume" and the Player and Bot turn text indicators. Both now follow the pixelated aesthetic using font "Press Start 2P"
- Changed the organization of the volume and music buttons near the bottom of the page. Now the Volume text and slider are underneath the control buttons, offering a more clean look that does not overwhelm the player.

These changes are incredibly important to immerse the player into the domino playful aesthetic.

### **Turn Indicator Image:**
image

### **Control Button and Volume Image:**
image

### CODE REVIEW

**Review by AngelCIICMorales — APPROVED** [review]
LGTM

**Comment by AngelCIICMorales** [comment]
I noticed some small things upon a second look. 
image
The text cuts of near the end.
image
The text for the score in all fives is in the old font.
image
Same is true for the draw dominoes

**Comment by AngelCIICMorales** [comment]
Could you please change that?

**Comment by DavidCuevas3** [comment]
Changed the remaining scores' text.
The input button for domino position was already cut off before my changes, this is due to "Enter the position of a domino" being too large a sentence for the element's size. I tried to change the width to accommodate the whole sentence, this however made the page decentralized, as the input box was much larger than other elements. I changed the text inside the input to "Enter domino position". This way the text can be completely read without cut off while also maintaining the relative width with other elements.

**Comment by AngelCIICMorales** [comment]
It looks good, however this still looks funny:
image

**Comment by DavidCuevas3** [comment]
It looked fine on my monitor, it may be an issue having to do with the aspect ratio.

**Review by PinkSylvie — APPROVED** [review]
Looks good!

**Pull request merged**
