### PR TITLE
Added Contact Us, FAQs, and Privacy Policy pages with routing.

### PR DESCRIPTION
**Pull request by Adriana-Isabel**
This merge request introduces three new informational pages for our Domino game website: Contact Us, Privacy Policy, and FAQs. These pages provide players with easy access to essential information, improving the overall user experience and ensuring transparency.

1. Contact Us:
- 	Provides users with contact information, including support email, phone number, and office hours.
- 	Helps players reach out for assistance or provide feedback.

2. Privacy Policy:
- 	Outlines how user data is collected, used, and protected on our platform.
- 	Ensures compliance with data privacy standards and builds trust with players.

3. FAQs:
- 	Answers common questions about gameplay, rules, and account setup.
- 	Helps users quickly find answers, reducing potential support inquiries.

### CODE REVIEW

**Comment by AngelCIICMorales** [comment]
image
This looks weird.

**Review by AngelCIICMorales — APPROVED** [review]
With a simple change this is good.

**Comment by Adriana-Isabel** [comment]
> image
> 
> This looks weird.

Yeah, it looked weirder before. I can fix it and make it look visually better for the next sprint.

**Review by PinkSylvie — APPROVED** [review]
Looks good!

**Pull request merged**
