### PR TITLE
Adding save system for multiplayer dominoes to main.

### PR DESCRIPTION
**Pull request by ilikecheese117**
Save game can be found in backend > src > gamestatus as the game status class.

The save game is a class called "Game Status" it does the following:
- Saves how the table currently looks
- Saves the hands of all players
- Saves who turn it is on exit so that the game can restart correctly in the future

### CODE REVIEW

**Comment by AngelCIICMorales** [comment]
How exactly does this work?

**Comment by AngelCIICMorales** [comment]
The title of the pull request should reflect the nature of the issue and code.

**Review by fernandopizarro1 — APPROVED** [review]
Ok, so the system was initialized. LGTM.

**Review by AngelCIICMorales — APPROVED** [review]
Lgtm.

**Review by G4vp — APPROVED** [review]
LGTM

**Pull request merged**
