### PR TITLE
Render rules and instructions when clicking on "Instruction" links in the Home Page

### PR DESCRIPTION
**Pull request by DavidCuevas3**
Clicking on the "Instructions" header and the "Click here for more in-depth instructions" link now renders the rules and instructions page which can be seen in GameState. This pull request now adds more functionality to the home page and makes the Multi Dominoes project a more complete product.

### CODE REVIEW

**Review by PinkSylvie — APPROVED** [review]
Everything looks and works fine

**Review by AngelCIICMorales — CHANGES_REQUESTED** [review]
It works well but its redundant for there to be 2 sets of the same instructions in the same page. Could you please get rid of the one at the top tab. Also, this task being urgency and difficulty 5 is not coherent with the group guidelines.

**Comment by DavidCuevas3** [comment]
Sure, I can remove the top instructions. However, in terms of the points, I could reduce difficulty to 4. The urgency however I consider prudent to leave at 5. Having non-responsive buttons and links in the home page is not a good look for the project and for its finalized state. Remedying that for me is considered a priority.

**Comment by DavidCuevas3** [comment]
Removed the "instructions" in the top tab as requested. Also took the liberty to fix the top FAQ link not being correctly set to "/faqs". Now all header links are functioning.

**Review by Joaquin939 — COMMENTED** [review]
LGTM!

**Review by Joaquin939 — APPROVED** [review]

**Comment by AngelCIICMorales** [comment]
Looks good now. How about this, if you add instructions for each of the game modes in their respective spaces (you can read the classic instructions while playing classic and the All fives while playing All fives, etc.) and change the homepage instructions to in general instructions on the website's features and how to start a match then I will give you all 25 points.

**Comment by AngelCIICMorales** [comment]
While you added get rid of the FAQ at the bottom tab so it can look nicer. There already exists a FAQ at the top.

**Comment by DavidCuevas3** [comment]
I can remove the FAQ at the bottom of the page. In regard to the instructions, adding the rest of the instructions is out of scope for this issue. The main objective was to make the links in the home page functional. I modified the points to be 20 instead of 25.

**Comment by DavidCuevas3** [comment]
Removed the FAQ link at the bottom of the page.

**Comment by AngelCIICMorales** [comment]
I'll give you 15. 5 urgency and 3 difficulty.

**Comment by DavidCuevas3** [comment]
Sounds good to me

**Review by AngelCIICMorales — APPROVED** [review]
LGTM

**Pull request merged**
