### PR TITLE
Enhanced Lobby Screens

### PR DESCRIPTION
**Pull request by igrv2003**
### This pull request focuses on refining the lobby screens’ design and responsiveness. Key updates include reorganizing and formatting the code, enhancing layout responsiveness, and aligning the color palette with the overall theme.

**Changes:**
1. Fixed text alignment issues across all screens.
2. Adjusted font sizes to ensure readability and visual balance.
3. Refined the color palette for consistency and better contrast.

4.	Updated the Selection Screen (Solo or Multiplayer).

Select Default
Select Responsive

5.	Improved the Solo Screen (Bot settings) with better alignment and font adjustments.
	
Solo Default
Solo Responsive

6.	Enhanced the Multiplayer Screen (Configure Room).
Multiplayer Default
Multiplayer Responsive

### CODE REVIEW

**Comment by AngelCIICMorales** [comment]
Please include draw dominoes: 
image

**Review by AngelCIICMorales — CHANGES_REQUESTED** [review]
Please add the draw dominoes game mode to the lobby.

**Comment by igrv2003** [comment]
Added "Draw Dominoes" option

image

**Review by AngelCIICMorales — APPROVED** [review]
LGTM

**Review by PinkSylvie — COMMENTED** [review]
Looks pretty good! Great work!

**Comment by igrv2003** [comment]
@Keiven-Soto @PinkSylvie me falta una aprobación más para hacer el merge. ¿Podrían echarle un vistazo y aprobarlo cuando puedan? ¡Gracias!

**Review by DavidCuevas3 — APPROVED** [review]

**Pull request merged**
