### PR TITLE
Completed the modifications

### PR DESCRIPTION
**Pull request by Joaquin939**
Screenshot 2024-11-06 at 10 34 52 AM
Screenshot 2024-11-06 at 10 31 31 AM
Here I was able to complete the modifications to the components of the home page so that it matches the other parts of the game. I used the same colors and changed the font family of all the text to 'Press Start 2P', sans-serif

### CODE REVIEW

**Comment by Joaquin939** [comment]
> * The top left icon looks off:
>   image
> * Here is a small grammar fix for the description: Dominoes is a tile game where the objective is to be the first to get rid of all your tiles or have the lowest score at the end. Players take turns placing tiles, connecting matching numbers at the ends of the chain of tiles on the table. If a player cannot make a move, they must skip their turn. The game continues until a player runs out of tiles or no more moves are possible. The winner scores points based on the tiles remaining in the opponents' hands, and the first player to reach a predetermined number of points wins the game.
> * The names don't fit inside the box:
>   image

Eso tiene que ser que la pagina no es responsive pero puedes ver que en mi screenshot se ve bien y caben los nombres. Eso quizás puede ser otro issue para la otra mitad del sprint. hacer que la pagina sea responsive.

**Comment by Joaquin939** [comment]
@AngelCIICMorales In this issue I only worked on changing fonts and colors to match the aesthetic of the game. Everything else you mentioned was already implemented and was untouched. For me, the logo has always looked like that. Also, I didn't write the description but I'll gladly correct the grammar issue you pointed out. And the responsiveness of the page is something that must be worked on separate from this issue in the next sprint because that is a very difficult task and we have very little time. Just wanted to clarify that the changes you requested are not part of this issue.

**Comment by Joaquin939** [comment]
@AngelCIICMorales Corrected the small grammar error that was in the description.

**Review by AngelCIICMorales — APPROVED** [review]
LGTM

**Comment by AngelCIICMorales** [comment]
> @AngelCIICMorales In this issue I only worked on changing fonts and colors to match the aesthetic of the game. Everything else you mentioned was already implemented and was untouched. For me, the logo has always looked like that. Also, I didn't write the description but I'll gladly correct the grammar issue you pointed out. And the responsiveness of the page is something that must be worked on separate from this issue in the next sprint because that is a very difficult task and we have very little time. Just wanted to clarify that the changes you requested are not part of this issue.

Here is how the logo used to look: 
image
Here is how to names used to appear: 
image
As you can see, these things weren't always there. Something in you changed made small issues.

**Comment by AngelCIICMorales** [comment]
This task is supposed to be worth 20 points. You can either work on the responsiveness of the home page or I can reduce the points to accommodate the work you have done.

**Comment by Joaquin939** [comment]
> This task is supposed to be worth 20 points. You can either work on the responsiveness of the home page or I can reduce the points to accommodate the work you have done.

I think it's best to reduce the points for this one and work on the responsiveness after this sprint.

**Review by PinkSylvie — APPROVED** [review]
Looks good!

**Pull request merged**
