### PR TITLE
Added the options to play against up to 3 bots and fixed how tiles are shown.

### PR DESCRIPTION
**Pull request by G4vp**
- Added 2 new buttons that allow you to choose whether you want to play against 2 bots or 3 bots.
- Added logic so bots lay sequentially after each turn.
- Fixed the bug where vertical tiles were not positioned correctly and fused together. I modified the code to use a grid that reads from the matrix with the table information, placing each domino in the correct position.

Current Game State Bugs:
   - Sometimes the bots get stuck because the Tail.Left is null for some reason.
   - The dominoes are positioned correctly, but their corners don't match with their neighbors.
   - The dominoes that are positioned vertically remain horizontal.
   - We need a button to pass your turn if you don't have playable dominoes.

### CODE REVIEW

**Review by fernandopizarro1 — APPROVED** [review]
LGTM

**Review by AngelCIICMorales — CHANGES_REQUESTED** [review]
Please fix the conflicts.

**Review by AngelCIICMorales — CHANGES_REQUESTED** [review]
The placement of the tiles makes the game unplayable. The dominoes are stacking on top of each other. Also, the dominoes of the opponents being on top of each other is not ideal. Could you make it, so the other players appear on the left and right side.
image

**Comment by G4vp** [comment]
Fixed the overlapping. The issue was probably due to using vh and vw for the grid's width and height instead of fixed values. Let me know if the bug continues.

**Comment by AngelCIICMorales** [comment]
I like how it looks now. Could you add a pass button to avoid a SoftLock?

**Comment by AngelCIICMorales** [comment]
I will raise your score for the issue to 25 if you do.

**Comment by G4vp** [comment]
> I like how it looks now. Could you add a pass button to avoid a SoftLock?
I've added the basic functionality for the pass turn button. Any improvements, such as hiding the button when a move can be made and showing it otherwise, can be worked on in the next milestone.

> I will raise your score for the issue to 25 if you do.
Thanks! But please don't do it. I think I have enough points from the tasks I've completed, so it's better to stay with the points I currently have, so others aren't affected.

**Review by AngelCIICMorales — APPROVED** [review]
Everything works as it should. Good work!

**Pull request merged**
