### PR TITLE
Added Home Page with the Header and the Footer

### PR DESCRIPTION
**Pull request by Adriana-Isabel**
Here is my branch with the issues #62 , #63 and #187 finished.

### CODE REVIEW

**Review by AngelCIICMorales — CHANGES_REQUESTED** [review]
Please resolve the conflicts.

**Comment by Adriana-Isabel** [comment]
Fixed the merging conflict.

**Comment by PinkSylvie** [comment]
I'm getting errors when I am trying to login after I visit the homepage, same happens when I try to signup and I am concerned that the page doesn't shrink and stretch when I shrink the tab.
image
image
image
@AngelCIICMorales @Adriana-Isabel

**Comment by Adriana-Isabel** [comment]
I only changed <Route path="/" element={<Home />} /> <Route path="/login" element={<Login />} /> for that way the first thing you see when running the game is the landing page. I didn't touch anything that has to do with the Log In (only the route in the App.js). I'll try and fix the shrink and stretch.

**Comment by PinkSylvie** [comment]
> I only changed <Route path="/" element={} /> <Route path="/login" element={} /> for that way the first thing you see when running the game is the landing page. I didn't touch anything that has to do with the Log In (only the route in the App.js). I'll try and fix the shrink and stretch.

No worries it was an issue on my end since I didn't have the .env file. Everything else looks good but I'm slightly concerned on the black background instead of blue and that the page doesn't shrink and stretch with the tab.

**Review by AngelCIICMorales — CHANGES_REQUESTED** [review]
The window seems to be too zoomed in. Could you please fix that?

**Comment by Adriana-Isabel** [comment]
What’s going on it’s that it stayed the same width as the normal screen, that’s why it looks zoomed in. But yes, I’m trying to fix it.

**Review by AngelCIICMorales — APPROVED** [review]
LGTM

**Review by PinkSylvie — APPROVED** [review]
It works better!

**Pull request merged**
