### PR TITLE
Integration of Login form with backend service

### PR DESCRIPTION
**Pull request by sandy-marrero**
This adds the missing functionality for proper authentication in our login forms, it also adds CORS to the backend service as it is required for the request between the frontend and backend to work iirc. Was tested locally and works correctly.

Screenshots:
1. Login:
image
2. Sign Up:
image
**Successfully Created the user in the database.**
image

### CODE REVIEW

**Review by AngelCIICMorales — CHANGES_REQUESTED** [review]
Please add the dependency cors.

**Comment by AngelCIICMorales** [comment]
I attempted to make an account, but nothing happened.

**Comment by sandy-marrero** [comment]
> I attempted to make an account, but nothing happened.

For it to work as is we need to add the changes from this PR to the deployed backend. To test it you have to initialize a local backend and change the backendUrl to localhost:8080.

**Comment by AngelCIICMorales** [comment]
The account can only be created in a future PR?

**Comment by sandy-marrero** [comment]
> Please add the dependency cors.

Fixed

**Comment by sandy-marrero** [comment]
> The account can only be created in a future PR?

Once this PR is merged accounts can be created and log in correctly. The issue is the version of the backend that is now deployed is missing CORS so requests are failing.

**Comment by AngelCIICMorales** [comment]
I checked and the cors dependency is still not on the request.

**Comment by FrancesC8** [comment]
> > The account can only be created in a future PR?
> 
> Once this PR is merged accounts can be created and log in correctly. The issue is the version of the backend that is now deployed is missing CORS so requests are failing.

It is not an issue, it is expected. I suggest to focus testing locally only, for now. After the PR is merged, let me know so I can deploy the latest version of the backend.

**Review by AngelCIICMorales — APPROVED** [review]
LGTM.

**Review by ebrain-mendoza121 — APPROVED** [review]

**Pull request merged**
