### PR TITLE
Add “Back To Home” Button to Contact Us Page

### PR DESCRIPTION
**Pull request by igrv2003**
This pull request adds a “Back To Home” button to the Contact Us page, providing users with an easy way to navigate back to the Home page. The button is styled to match the site’s theme.
Multi Dominoes

### CODE REVIEW

**Review by DavidCuevas3 — APPROVED** [review]
LGTM. Makes the user experience a lot more fluid.

**Comment by AngelCIICMorales** [comment]
It works well. If you can do the same thing for the FAQ and Privacy policy, I'll give you 12 points. Also, could you resize each of these screens so the entire message so its fits on the screen without scrolling?

**Comment by AngelCIICMorales** [comment]
I you fix the scrolling I'll give you 15.

**Comment by igrv2003** [comment]
Hi @AngelCIICMorales,

I’ve added the “Back to Home” button to both the FAQs and Privacy Policy pages as requested. However, I couldn’t fully figure out how to ensure the content fits the screen without scrolling. Would it be fair to adjust the proposed points to 8 in this case?

**Comment by igrv2003** [comment]
Multi Dominoes · 3 16pm · 11-25
Multi Dominoes · 3 15pm · 11-25

**Comment by AngelCIICMorales** [comment]
Could you take the extra time to do it? If not, I'll give you the 8 points.

**Comment by igrv2003** [comment]
@AngelCIICMorales I’m under pressure from other classes and can’t take extra time for the screen fit adjustments. Could we proceed with the 8 points?

**Review by AngelCIICMorales — APPROVED** [review]
LGTM

**Pull request merged**
