### PR TITLE
Add player avatars and improve game layout

### PR DESCRIPTION
**Pull request by Saul-Caban-UPRM**
Enhanced the visual representation of players by adding avatar images for:
Main bot (blue) at the top
Second bot (green) on the left side (visible in 2 or 3 bot modes)
Third bot (yellow) on the right side (visible in 3 bot mode)
Player (red) at the bottom

### CODE REVIEW

**Comment by AngelCIICMorales** [comment]
In 2 bot mode it looks fine: 
image

**Review by AngelCIICMorales — CHANGES_REQUESTED** [review]
The textures look squinched:
image

**Comment by Saul-Caban-UPRM** [comment]
I added a scroll bar that moves horizontally and made the texture stay it size regardless of window size.

**Review by PinkSylvie — APPROVED** [review]
Looks good to me!

**Review by AngelCIICMorales — CHANGES_REQUESTED** [review]
Can you make the gamescreen smaller?
image

**Comment by Saul-Caban-UPRM** [comment]
I made the game screen smaller by making the gameboard smaller and making the bots dominoes smaller, and changing the size of the domino displayed at the game board. Also fixed issue with the toast messages not appearing properly on the top right of the screen. Also made the all the bots dominoes sizes consistent this time.

**Review by AngelCIICMorales — APPROVED** [review]
LGTM

**Pull request merged**
