### PR TITLE
Changes to deploy backend server

### PR DESCRIPTION
**Pull request by FrancesC8**
_**IMPORTANT**_: Please change the connection string environment variable name from `MONGODB_CONNECTION_STRING` to `MONGODB_URI` in your `.env` file. In order for the backend to work locally.

Added the necessary changes to deploy the backend server and the mongodb database. Hosting them in cloud environments (Vercel for the server and MongoDb Atlas for the database). I chose these options because they offer free tiers and they integrate easily.

The backend is hosted and connected to the database here: [https://multi-dominoes.vercel.app/](https://multi-dominoes.vercel.app/).

### CODE REVIEW

**Comment by AngelCIICMorales** [comment]
I tried opening the link but got this message: Cannot GET /

**Comment by FrancesC8** [comment]
> I tried opening the link but got this message: Cannot GET /

I added a dummy response for '/' path. It should not fail anymore and I redeployed everything with latest changes, try it again [https://multi-dominoes.vercel.app/](https://multi-dominoes.vercel.app/).

I also fixed merge conflicts

**Review by AngelCIICMorales — APPROVED** [review]
LGTM!

**Review by sandy-marrero — APPROVED** [review]

**Review by JadiellMV — APPROVED** [review]
Looks fine!

**Pull request merged**
