### PR TITLE
#69 achievement manager and #67 Rule engine

### PR DESCRIPTION
**Pull request by nsfrontera**
made achievement and made them appear using toastify

### CODE REVIEW

**Review by fernandopizarro1 — COMMENTED** [review]
Everything looks good, now just stay alert in case of merge conflicts from the PR before this one.

**Review by AngelCIICMorales — CHANGES_REQUESTED** [review]
There are merge conflicts.

**Comment by AngelCIICMorales** [comment]
ERROR in ./src/gamestate/AchievementManager.js 4:0-39
Module not found: Error: Can't resolve 'react-toastify' in 'C:\Users\Angel\Desktop\Experiment\semester-project-multiplayer-dominoes\frontend\src\gamestate'
ERROR in ./src/gamestate/experimentalGame.js 13:0-48
Module not found: Error: Can't resolve 'react-toastify' in 'C:\Users\Angel\Desktop\Experiment\semester-project-multiplayer-dominoes\frontend\src\gamestate'
ERROR in ./src/gamestate/experimentalGame.js 14:0-47
Module not found: Error: Can't resolve 'react-toastify/dist/ReactToastify.css' in 'C:\Users\Angel\Desktop\Experiment\semester-project-multiplayer-dominoes\frontend\src\gamestate'

**Comment by AngelCIICMorales** [comment]
Starting the development server...

One of your dependencies, babel-preset-react-app, is importing the
"@babel/plugin-proposal-private-property-in-object" package without
declaring it in its dependencies. This is currently working because
Compiled with warnings.

[eslint]
src\App.js
  Line 1:8:  'logo' is defined but never used  no-unused-vars

src\gamestate\Bot.js
  Line 1:10:  'Table' is defined but never used   no-unused-vars
  Line 1:25:  'Domino' is defined but never used  no-unused-vars

src\gamestate\experimentalGame.js
  Line 150:8:  React Hook useEffect has missing dependencies: 'botData', 'botPlayTurn', 'playerDominoIndex', and 'tableData'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

WARNING in [eslint]
src\App.js
  Line 1:8:  'logo' is defined but never used  no-unused-vars

Compiled with warnings.

[eslint]
src\App.js
  Line 1:8:  'logo' is defined but never used  no-unused-vars

src\gamestate\Bot.js
  Line 1:10:  'Table' is defined but never used   no-unused-vars
  Line 1:25:  'Domino' is defined but never used  no-unused-vars

src\gamestate\experimentalGame.js
  Line 151:8:  React Hook useEffect has missing dependencies: 'botData', 'botPlayTurn', 'playerDominoIndex', and 'tableData'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

WARNING in [eslint]
src\App.js
  Line 1:8:  'logo' is defined but never used  no-unused-vars

Compiled with warnings.

[eslint]
src\App.js
  Line 1:8:  'logo' is defined but never used  no-unused-vars

src\gamestate\Bot.js
  Line 1:10:  'Table' is defined but never used   no-unused-vars
  Line 1:25:  'Domino' is defined but never used  no-unused-vars

src\gamestate\experimentalGame.js
  Line 162:8:  React Hook useEffect has missing dependencies: 'botData', 'botPlayTurn', 'playerDominoIndex', and 'tableData'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

WARNING in [eslint]
src\App.js
  Line 1:8:  'logo' is defined but never used  no-unused-vars

Failed to compile.

Module not found: Error: Can't resolve 'react-toastify' in 'C:\Users\Angel\Desktop\Experiment\semester-project-multiplayer-dominoes\frontend\src\gamestate'
WARNING in [eslint]
src\App.js
  Line 1:8:  'logo' is defined but never used  no-unused-vars

src\gamestate\Bot.js
  Line 1:10:  'Table' is defined but never used   no-unused-vars
  Line 1:25:  'Domino' is defined but never used  no-unused-vars

src\gamestate\experimentalGame.js
  Line 47:8:   React Hook useEffect has missing dependencies: 'achievementManager' and 'initialPlayerHand'. Either include them or remove the dependency array                                                        react-hooks/exhaustive-deps
  Line 181:8:  React Hook useEffect has missing dependencies: 'achievementManager', 'botData', 'botPlayTurn', 'playerDominoIndex', 'ruleEngine', and 'tableData'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

ERROR in ./src/gamestate/AchievementManager.js 4:0-39
Module not found: Error: Can't resolve 'react-toastify' in 'C:\Users\Angel\Desktop\Experiment\semester-project-multiplayer-dominoes\frontend\src\gamestate'

ERROR in ./src/gamestate/experimentalGame.js 13:0-48
Module not found: Error: Can't resolve 'react-toastify' in 'C:\Users\Angel\Desktop\Experiment\semester-project-multiplayer-dominoes\frontend\src\gamestate'

ERROR in ./src/gamestate/experimentalGame.js 14:0-47
Module not found: Error: Can't resolve 'react-toastify/dist/ReactToastify.css' in 'C:\Users\Angel\Desktop\Experiment\semester-project-multiplayer-dominoes\frontend\src\gamestate'

webpack compiled with 3 errors and 1 warning

 *  History restored 

PS C:\Users\Angel\Desktop\Experiment\semester-project-multiplayer-dominoes> cd frontend
PS C:\Users\Angel\Desktop\Experiment\semester-project-multiplayer-dominoes\frontend> npm start  
Failed to compile.

Module not found: Error: Can't resolve 'react-toastify' in 'C:\Users\Angel\Desktop\Experiment\semester-project-multiplayer-dominoes\frontend\src\gamestate'
WARNING in [eslint]
src\App.js
  Line 1:8:  'logo' is defined but never used  no-unused-vars

src\gamestate\Bot.js
  Line 1:10:  'Table' is defined but never used   no-unused-vars
  Line 1:25:  'Domino' is defined but never used  no-unused-vars

src\gamestate\experimentalGame.js
  Line 47:8:   React Hook useEffect has missing dependencies: 'achievementManager' and 'initialPlayerHand'. Either include them or remove the dependency array                                                        react-hooks/exhaustive-deps
  Line 181:8:  React Hook useEffect has missing dependencies: 'achievementManager', 'botData', 'botPlayTurn', 'playerDominoIndex', 'ruleEngine', and 'tableData'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

ERROR in ./src/gamestate/AchievementManager.js 4:0-39
Module not found: Error: Can't resolve 'react-toastify' in 'C:\Users\Angel\Desktop\Experiment\semester-project-multiplayer-dominoes\frontend\src\gamestate'

ERROR in ./src/gamestate/experimentalGame.js 13:0-48
Module not found: Error: Can't resolve 'react-toastify' in 'C:\Users\Angel\Desktop\Experiment\semester-project-multiplayer-dominoes\frontend\src\gamestate'

ERROR in ./src/gamestate/experimentalGame.js 14:0-47
Module not found: Error: Can't resolve 'react-toastify/dist/ReactToastify.css' in 'C:\Users\Angel\Desktop\Experiment\semester-project-multiplayer-dominoes\frontend\src\gamestate'

**Comment by nsfrontera** [comment]
haz npm install, puse una nueva dependencia

**Comment by fernandopizarro1** [comment]
> Starting the development server...
> 
> One of your dependencies, babel-preset-react-app, is importing the "@babel/plugin-proposal-private-property-in-object" package without declaring it in its dependencies. This is currently working because Compiled with warnings.
> 
> [eslint] src\App.js Line 1:8: 'logo' is defined but never used no-unused-vars
> 
> src\gamestate\Bot.js Line 1:10: 'Table' is defined but never used no-unused-vars Line 1:25: 'Domino' is defined but never used no-unused-vars
> 
> src\gamestate\experimentalGame.js Line 150:8: React Hook useEffect has missing dependencies: 'botData', 'botPlayTurn', 'playerDominoIndex', and 'tableData'. Either include them or remove the dependency array react-hooks/exhaustive-deps
> 
> Search for the keywords to learn more about each warning. To ignore, add // eslint-disable-next-line to the line before.
> 
> WARNING in [eslint] src\App.js Line 1:8: 'logo' is defined but never used no-unused-vars
> 
> Compiled with warnings.
> 
> [eslint] src\App.js Line 1:8: 'logo' is defined but never used no-unused-vars
> 
> src\gamestate\Bot.js Line 1:10: 'Table' is defined but never used no-unused-vars Line 1:25: 'Domino' is defined but never used no-unused-vars
> 
> src\gamestate\experimentalGame.js Line 151:8: React Hook useEffect has missing dependencies: 'botData', 'botPlayTurn', 'playerDominoIndex', and 'tableData'. Either include them or remove the dependency array react-hooks/exhaustive-deps
> 
> Search for the keywords to learn more about each warning. To ignore, add // eslint-disable-next-line to the line before.
> 
> WARNING in [eslint] src\App.js Line 1:8: 'logo' is defined but never used no-unused-vars
> 
> Compiled with warnings.
> 
> [eslint] src\App.js Line 1:8: 'logo' is defined but never used no-unused-vars
> 
> src\gamestate\Bot.js Line 1:10: 'Table' is defined but never used no-unused-vars Line 1:25: 'Domino' is defined but never used no-unused-vars
> 
> src\gamestate\experimentalGame.js Line 162:8: React Hook useEffect has missing dependencies: 'botData', 'botPlayTurn', 'playerDominoIndex', and 'tableData'. Either include them or remove the dependency array react-hooks/exhaustive-deps
> 
> Search for the keywords to learn more about each warning. To ignore, add // eslint-disable-next-line to the line before.
> 
> WARNING in [eslint] src\App.js Line 1:8: 'logo' is defined but never used no-unused-vars
> 
> Failed to compile.
> 
> Module not found: Error: Can't resolve 'react-toastify' in 'C:\Users\Angel\Desktop\Experiment\semester-project-multiplayer-dominoes\frontend\src\gamestate' WARNING in [eslint] src\App.js Line 1:8: 'logo' is defined but never used no-unused-vars
> 
> src\gamestate\Bot.js Line 1:10: 'Table' is defined but never used no-unused-vars Line 1:25: 'Domino' is defined but never used no-unused-vars
> 
> src\gamestate\experimentalGame.js Line 47:8: React Hook useEffect has missing dependencies: 'achievementManager' and 'initialPlayerHand'. Either include them or remove the dependency array react-hooks/exhaustive-deps Line 181:8: React Hook useEffect has missing dependencies: 'achievementManager', 'botData', 'botPlayTurn', 'playerDominoIndex', 'ruleEngine', and 'tableData'. Either include them or remove the dependency array react-hooks/exhaustive-deps
> 
> ERROR in ./src/gamestate/AchievementManager.js 4:0-39 Module not found: Error: Can't resolve 'react-toastify' in 'C:\Users\Angel\Desktop\Experiment\semester-project-multiplayer-dominoes\frontend\src\gamestate'
> 
> ERROR in ./src/gamestate/experimentalGame.js 13:0-48 Module not found: Error: Can't resolve 'react-toastify' in 'C:\Users\Angel\Desktop\Experiment\semester-project-multiplayer-dominoes\frontend\src\gamestate'
> 
> ERROR in ./src/gamestate/experimentalGame.js 14:0-47 Module not found: Error: Can't resolve 'react-toastify/dist/ReactToastify.css' in 'C:\Users\Angel\Desktop\Experiment\semester-project-multiplayer-dominoes\frontend\src\gamestate'
> 
> webpack compiled with 3 errors and 1 warning
> 
> * History restored
> 
> PS C:\Users\Angel\Desktop\Experiment\semester-project-multiplayer-dominoes> cd frontend PS C:\Users\Angel\Desktop\Experiment\semester-project-multiplayer-dominoes\frontend> npm start Failed to compile.
> 
> Module not found: Error: Can't resolve 'react-toastify' in 'C:\Users\Angel\Desktop\Experiment\semester-project-multiplayer-dominoes\frontend\src\gamestate' WARNING in [eslint] src\App.js Line 1:8: 'logo' is defined but never used no-unused-vars
> 
> src\gamestate\Bot.js Line 1:10: 'Table' is defined but never used no-unused-vars Line 1:25: 'Domino' is defined but never used no-unused-vars
> 
> src\gamestate\experimentalGame.js Line 47:8: React Hook useEffect has missing dependencies: 'achievementManager' and 'initialPlayerHand'. Either include them or remove the dependency array react-hooks/exhaustive-deps Line 181:8: React Hook useEffect has missing dependencies: 'achievementManager', 'botData', 'botPlayTurn', 'playerDominoIndex', 'ruleEngine', and 'tableData'. Either include them or remove the dependency array react-hooks/exhaustive-deps
> 
> ERROR in ./src/gamestate/AchievementManager.js 4:0-39 Module not found: Error: Can't resolve 'react-toastify' in 'C:\Users\Angel\Desktop\Experiment\semester-project-multiplayer-dominoes\frontend\src\gamestate'
> 
> ERROR in ./src/gamestate/experimentalGame.js 13:0-48 Module not found: Error: Can't resolve 'react-toastify' in 'C:\Users\Angel\Desktop\Experiment\semester-project-multiplayer-dominoes\frontend\src\gamestate'
> 
> ERROR in ./src/gamestate/experimentalGame.js 14:0-47 Module not found: Error: Can't resolve 'react-toastify/dist/ReactToastify.css' in 'C:\Users\Angel\Desktop\Experiment\semester-project-multiplayer-dominoes\frontend\src\gamestate'

You have to do npm install again, the dependencies are in the .json file

**Comment by nsfrontera** [comment]
y lo de One of your dependencies, babel-preset-react-app, is importing the
"@babel/plugin-proposal-private-property-in-object" package without
declaring it in its dependencies.  no estoy seguro porque no trabaje con eso

**Review by AngelCIICMorales — APPROVED** [review]
LGTM.

**Review by fernandopizarro1 — APPROVED** [review]
LGTM!

**Comment by nsfrontera** [comment]
mil thx!

**Pull request merged**
